### ISSUE TITLE
add barcode to idcard

### ISSUE THREAD

**Issue by pra33g** [sdc-msi/idcardgenerator#4]
add a barcode with following specification:
Type:Code128
Format:` <FNC1>[Enrollment]`
Example: `<FNC1>06414902020`
Generate enrollment based on following criteria:
rrr-ccc-yyyy

rrr - rank
ccc - course code
yyyy - year of entry

**Comment by 0xNoor** [comment]
Added the functionality in the commit ID - 7fe7ef9a8903fa0300ac3c061753a7f89e642028
